# Generated by Django 4.2.5 on 2023-10-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RatingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingtable',
            name='id',
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='Name',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
