# Generated by Django 4.2.5 on 2023-10-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RatingApp', '0002_remove_ratingtable_id_alter_ratingtable_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingtable',
            name='project22',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project23',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project24',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project25',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project26',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project27',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project28',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project29',
        ),
        migrations.RemoveField(
            model_name='ratingtable',
            name='project30',
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='project1',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Generating strong password using python', max_length=2),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='project10',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Emergency Service Locator using python', max_length=2),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='project11',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Develop the English Knowledge of Children using python', max_length=2),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='project12',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Virtual Drivers using Python', max_length=2),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='project13',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Portfolio Management using Py,Html', max_length=2),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='project14',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Chatbot development using Python', max_length=2),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='project15',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Language Translator using Java', max_length=2),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='project16',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Online voting System using Python', max_length=2),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='project17',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Route Analysis using Python', max_length=2),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='project18',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Converting Text to audio & Audio to text using python', max_length=2),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='project19',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Facemask Detection using python', max_length=2),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='project2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Children vaccination management using python', max_length=2),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='project20',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Incident Reporter using Python', max_length=2),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='project21',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text="Tracks of people's Creditscores & Dues using Python", max_length=2),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='project3',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Traffic prediction using python', max_length=2),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='project4',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Webdevelopment using HTML,Css,Py,PostgreSQL', max_length=2),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='project5',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Medcare development using python', max_length=2),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='project6',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Calculator App using python', max_length=2),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='project7',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Logic Game using python', max_length=2),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='project8',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Schedule Messenger using python', max_length=2),
        ),
        migrations.AlterField(
            model_name='ratingtable',
            name='project9',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='Housing Society Management System using Java', max_length=2),
        ),
    ]
